NUMBER_OF_FALSE_ANSWERS = 2 # total of 3 answers
MAX_NAME_LENGTH = 32 # characters
DATABASE_UPDATE_COOLDOWN = 30  # secs
GUESS_COMMAND = "!guess"
SCOREBOARD_COMMAND = "!scores"
PREDICTIBILITY_COMMAND = "!authors"
MIXES_COMMAND = "!mixes"
